# @base_url=http://localhost:8085

# POST {{base_url}}/todos
# Content-Type: application/json

# {
#     "text": "test 1"
# }


POST http://localhost:8085/todos
Content-type: application/json

{
    "text": "test 2"
}
 